apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eats-profile
spec:
  rules:
    - host: eats-profile.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eats-profile
                port:
                  number: 3000
