apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-search-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-search-frontend
  template:
    metadata:
      labels:
        app: cart-search-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/molam-eats/cart-search-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cart-search-frontend
spec:
  selector:
    app: cart-search-frontend
  ports:
    - port: 80
      targetPort: 80
