apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eats-surge-sm
spec:
  selector:
    matchLabels:
      app: eats-surge
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
