apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eats-menu-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: eats-menu
  namespaceSelector:
    matchNames:
      - molam
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
