apiVersion: v1
kind: Secret
metadata:
  name: eats-secrets
type: Opaque
stringData:
  DATABASE_URL: "REPLACE_ME_DATABASE_URL"
  KAFKA_BROKERS: "REPLACE_ME_KAFKA_BROKERS"
  FATIMA_URL: "REPLACE_ME_FATIMA_URL"
  FATIMA_KEY: "REPLACE_ME_FATIMA_KEY"
  MOLAM_ID_URL: "REPLACE_ME_MOLAM_ID_URL"
  MOLAM_ID_TOKEN: "REPLACE_ME_MOLAM_ID_TOKEN"
