apiVersion: v1
kind: Service
metadata:
  name: moderation-service
  labels:
    app: moderation
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
      name: http
  selector:
    app: moderation
