apiVersion: v1
kind: Service
metadata:
  name: eats-plans
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: eats-plans
