apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eats-cart-admin
spec:
  selector:
    matchLabels:
      app: eats-cart-admin
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
