apiVersion: v1
kind: Service
metadata:
  name: eats-surge
  labels:
    app: eats-surge
spec:
  selector:
    app: eats-surge
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
  type: ClusterIP
