apiVersion: apps/v1
kind: Deployment
metadata:
  name: eats-catalog
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: eats-catalog
  template:
    metadata:
      labels:
        app: eats-catalog
    spec:
      containers:
        - name: eats-catalog
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - secretRef:
                name: eats-catalog-secret
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
