apiVersion: v1
kind: Secret
metadata:
  name: eats-catalog-secret
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  KAFKA_BROKERS: {{ .Values.env.KAFKA_BROKERS | quote }}
  FATIMA_URL: {{ .Values.env.FATIMA_URL | quote }}
  FATIMA_KEY: {{ .Values.env.FATIMA_KEY | quote }}
  OBJECT_STORE_ENDPOINT: {{ .Values.env.OBJECT_STORE_ENDPOINT | quote }}
  OBJECT_STORE_KEY: {{ .Values.env.OBJECT_STORE_KEY | quote }}
  OBJECT_STORE_SECRET: {{ .Values.env.OBJECT_STORE_SECRET | quote }}
