apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eats-refunds-monitor
spec:
  selector:
    matchLabels:
      app: eats-refunds
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
